name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP_NAME: "green-fork-rg"
  AKS_CLUSTER_NAME: "green-fork-aks-cluster"
  # ACR_NAME is stored as a secret

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/productcatalogservice:latest ./src/productcatalogservice
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/productcatalogservice:latest

          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/cartservice:latest ./src/cartservice
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/cartservice:latest

          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./src/frontend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
          # Add similar build/push commands for all other services...
          # For brevity, only showing a few here. The full set is in the original repo's skaffold.yaml.
          # This simplified version will get the main components working.

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Deploy to AKS
        run: |
          sed -i 's|gcr.io/google-samples/microservices-demo|${{ secrets.ACR_NAME }}.azurecr.io|g' ./kubernetes-manifests/kubernetes-manifests.yaml
          kubectl apply -f ./kubernetes-manifests/kubernetes-manifests.yaml